"""Variety Governor — enforces visual and kinetic diversity across scene plans.

Prevents superficial repetition, enforces anti-patterns from art direction,
and calculates a rigorous variety score (0-100).
"""
from __future__ import annotations

import re
from typing import Any
from pydantic import BaseModel, Field


class VarietyFinding(BaseModel):
    """Structured finding for visual variety violations."""
    code: str
    severity: str  # "critical", "warning"
    message: str
    evidence: str = ""
    correction: str = ""


class VarietyReport(BaseModel):
    """Report generated by the Variety Governor."""
    variety_score: float = Field(ge=0.0, le=100.0)
    findings: list[VarietyFinding] = Field(default_factory=list)
    scene_type_distribution: dict[str, int] = Field(default_factory=dict)
    technique_usage: dict[str, int] = Field(default_factory=dict)

    @property
    def is_valid(self) -> bool:
        return not any(f.severity == "critical" for f in self.findings)


class VarietyGovernor:
    """Monitors and governs scene sequence diversity."""

    def __init__(self, min_distinct_techniques: int = 3) -> None:
        self.min_distinct_techniques = min_distinct_techniques

    def evaluate(
        self,
        scenes: list[dict[str, Any]],
        art_direction: dict[str, Any] | None = None,
    ) -> VarietyReport:
        findings: list[VarietyFinding] = []
        if not scenes:
            return VarietyReport(
                variety_score=0.0,
                findings=[VarietyFinding(code="NO_SCENES", severity="critical", message="No scenes provided.")],
            )

        num_scenes = len(scenes)
        types = [s.get("type", "animation") for s in scenes]
        techniques = [s.get("visual_technique", "diagram_reveal") for s in scenes]
        compositions = [
            (s.get("composition_intent") or s.get("composition") or "centered").strip().lower()
            for s in scenes
        ]

        # Count distributions
        type_dist: dict[str, int] = {}
        for t in types:
            type_dist[t] = type_dist.get(t, 0) + 1

        tech_dist: dict[str, int] = {}
        for tech in techniques:
            tech_dist[tech] = tech_dist.get(tech, 0) + 1

        # 1. Rule: No 3 consecutive identical scene types
        for i in range(num_scenes - 2):
            if types[i] == types[i + 1] == types[i + 2]:
                findings.append(
                    VarietyFinding(
                        code="CONSECUTIVE_IDENTICAL_SCENE_TYPES",
                        severity="critical",
                        message=f"3 consecutive identical scene types detected: {types[i]!r} at scenes {i+1}-{i+3}.",
                        evidence=f"scenes[{i}:{i+3}] = {types[i:i+3]}",
                        correction="Alternate scene types (e.g. blend animation, diagram, and broll).",
                    )
                )

        # 2. Rule: No 3 consecutive identical visual techniques
        for i in range(num_scenes - 2):
            if techniques[i] == techniques[i + 1] == techniques[i + 2]:
                findings.append(
                    VarietyFinding(
                        code="CONSECUTIVE_IDENTICAL_TECHNIQUES",
                        severity="critical",
                        message=f"3 consecutive identical visual techniques detected: {techniques[i]!r} at scenes {i+1}-{i+3}.",
                        evidence=f"scenes[{i}:{i+3}] = {techniques[i:i+3]}",
                        correction="Vary the storytelling mechanism across scenes.",
                    )
                )

        # 3. Rule: No 3 consecutive identical composition geometries
        for i in range(num_scenes - 2):
            # Check if composition strings share the same core geometry
            c0, c1, c2 = compositions[i], compositions[i + 1], compositions[i + 2]
            if c0 == c1 == c2 and c0:
                findings.append(
                    VarietyFinding(
                        code="CONSECUTIVE_IDENTICAL_COMPOSITIONS",
                        severity="critical",
                        message=f"3 consecutive identical composition intents detected: {c0!r} at scenes {i+1}-{i+3}.",
                        evidence=f"scenes[{i}:{i+3}] = [{c0}, {c1}, {c2}]",
                        correction="Vary framing (e.g. shift from centered to split-screen, isometric, or macro).",
                    )
                )

        # 4. Rule: At least 3 distinct visual techniques across video
        distinct_techs = set(techniques)
        if len(distinct_techs) < self.min_distinct_techniques:
            findings.append(
                VarietyFinding(
                    code="INSUFFICIENT_DISTINCT_TECHNIQUES",
                    severity="critical",
                    message=f"Video uses only {len(distinct_techs)} distinct visual techniques (minimum {self.min_distinct_techniques} required).",
                    evidence=f"techniques={list(distinct_techs)}",
                    correction="Incorporate diverse techniques such as analogy_visualization, timeline_progression, or scale_transition.",
                )
            )

        # 5. Art Direction anti-patterns enforcement
        if art_direction:
            anti_patterns = [p.lower() for p in art_direction.get("anti_patterns", [])]
            for ap in anti_patterns:
                # Anti-pattern: no floating cards
                if "floating card" in ap:
                    card_scenes = [
                        idx + 1 for idx, c in enumerate(compositions)
                        if "card" in c or "floating" in c
                    ]
                    if len(card_scenes) > 1:
                        findings.append(
                            VarietyFinding(
                                code="ANTI_PATTERN_VIOLATION_CARDS",
                                severity="critical",
                                message=f"Violated anti-pattern {ap!r}: detected floating cards in multiple scenes {card_scenes}.",
                                evidence=f"card_scenes={card_scenes}",
                                correction="Replace floating card compositions with physical environments or native diagrams.",
                            )
                        )

                # Anti-pattern: no text-only explanation
                if "text-only" in ap or "text only" in ap:
                    for idx, s in enumerate(scenes):
                        stype = s.get("type", "")
                        action = (s.get("subject_action") or "").strip().lower()
                        assets = s.get("required_assets", [])
                        if stype == "text_card" and (not action or not assets):
                            findings.append(
                                VarietyFinding(
                                    code="ANTI_PATTERN_VIOLATION_TEXT_ONLY",
                                    severity="critical",
                                    message=f"Scene {idx+1} is text-only without a visual anchor, violating anti-pattern: {ap!r}.",
                                    evidence=f"scene_{idx+1}_type={stype}",
                                    correction="Add active visual anchors, diagram elements, or kinetic motion.",
                                )
                            )

                # Anti-pattern: no identical centered hero
                if "identical centered hero" in ap or "centered layout" in ap:
                    centered_count = sum(1 for c in compositions if "center" in c)
                    if centered_count > num_scenes * 0.5:
                        findings.append(
                            VarietyFinding(
                                code="ANTI_PATTERN_VIOLATION_CENTERED_HERO",
                                severity="critical",
                                message=f"Violated anti-pattern {ap!r}: {centered_count}/{num_scenes} scenes use centered layout.",
                                evidence=f"centered_ratio={centered_count/num_scenes:.2f}",
                                correction="Use asymmetrical, progressive, or split-screen layouts.",
                            )
                        )

        # 6. Calculate Variety Score (0-100)
        # Components:
        # - technique diversity: distinct techniques / min(num_scenes, 6) -> 40 pts
        # - scene type diversity: distinct types / min(num_scenes, 4) -> 30 pts
        # - camera intent diversity -> 15 pts
        # - motion intent diversity -> 15 pts
        cameras = {s.get("camera_intent") for s in scenes if s.get("camera_intent")}
        motions = {s.get("motion_intent") for s in scenes if s.get("motion_intent")}

        tech_ratio = min(1.0, len(distinct_techs) / max(3, min(num_scenes, 5)))
        type_ratio = min(1.0, len(set(types)) / max(2, min(num_scenes, 4)))
        cam_ratio = min(1.0, len(cameras) / max(2, min(num_scenes, 4)))
        motion_ratio = min(1.0, len(motions) / max(2, min(num_scenes, 4)))

        raw_score = (tech_ratio * 40.0) + (type_ratio * 30.0) + (cam_ratio * 15.0) + (motion_ratio * 15.0)

        # Deduct penalties for critical findings
        penalty = sum(25.0 for f in findings if f.severity == "critical")
        variety_score = max(0.0, min(100.0, round(raw_score - penalty, 1)))

        return VarietyReport(
            variety_score=variety_score,
            findings=findings,
            scene_type_distribution=type_dist,
            technique_usage=tech_dist,
        )
