"""Phase 10 Research Engine — live retrieval orchestrator.

Pipeline:
  Topic
  → Query Expansion
  → Live Search across Selected/Multi Providers
  → Source Deduplication + Tier Assignment
  → Claim Extraction from Titles
  → Cross-Source Verification
  → Visual Fact & Entity Extraction (Phase 10.3)
  → Story Ranking & Top-N Selection (Phase 10.4)
  → ResearchPack

INVARIANTS:
- If no live provider is configured → ResearchPack with mode=UNAVAILABLE.
- URLs are NEVER generated by an LLM.
- Evidence MUST come from retrieved sources.
- LLM is NOT called anywhere in this module.
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

from .models import ClaimStatus, ResearchMode, ResearchPack, SourceRecord
from .query_expander import expand_queries
from .verifier import build_claims
from .visual_extractor import extract_visual_facts
from .story_ranker import rank_stories
from .providers.base import LiveResearchUnavailableError, SearchProvider
from .providers.registry import get_provider
from .fetcher import infer_tier


def _normalize_url(url: str) -> str:
    """Strip query params and fragments for deduplication."""
    try:
        p = urlparse(url)
        return f"{p.scheme}://{p.netloc}{p.path}".rstrip("/")
    except Exception:
        return url


def _deduplicate_sources(raw_results: list) -> list[SourceRecord]:
    """Deduplicate by normalized URL, assign source_ids and tiers."""
    seen: dict[str, SourceRecord] = {}
    counter = 0
    for r in raw_results:
        key = _normalize_url(r.url)
        if key in seen:
            continue
        counter += 1
        tier = 1 if r.source_type == "official" else infer_tier(r.url)
        seen[key] = SourceRecord(
            source_id=f"src_{counter:03d}",
            title=r.title,
            publisher=r.publisher or _publisher_from_url(r.url),
            url=r.url,
            published_at=r.published_at,
            retrieved_at=r.retrieved_at,
            source_type=r.source_type,
            query=r.query,
            retrieval_provider=r.provider,
            tier=tier,
            snippet=r.snippet,
        )
    # Sort by tier then by source_id
    return sorted(seen.values(), key=lambda s: (s.tier, s.source_id))


def _publisher_from_url(url: str) -> str:
    try:
        host = urlparse(url).hostname or ""
        return host.removeprefix("www.")
    except Exception:
        return ""


def research(
    topic: str,
    *,
    freshness: Optional[str] = None,  # "1d", "7d", "30d", "1y"
    max_results_per_query: int = 8,
    provider: Optional[SearchProvider] = None,
    provider_name: Optional[str] = None,
    top_n_stories: int = 5,
) -> ResearchPack:
    """Run the full research pipeline for a topic.
    
    Returns a ResearchPack. If no live provider is configured, returns
    a ResearchPack with research_mode=UNAVAILABLE rather than fabricating data.
    """
    researched_at = datetime.now(timezone.utc).isoformat()

    # Resolve provider
    if provider is None:
        try:
            if provider_name is not None:
                provider = get_provider(provider_name)
            else:
                provider = get_provider()
        except LiveResearchUnavailableError as exc:
            return ResearchPack(
                topic=topic,
                researched_at=researched_at,
                research_mode=ResearchMode.UNAVAILABLE,
                status="LIVE_RESEARCH_UNAVAILABLE",
                provider=None,
                queries_issued=[],
                claims=[],
                sources=[],
                stories=[],
                top_stories=[],
            )

    # Generate targeted queries
    queries = expand_queries(topic)

    # Execute searches
    all_raw: list = []
    queries_issued: list[str] = []
    for q in queries:
        try:
            results = provider.search(q, max_results=max_results_per_query, freshness=freshness)
            all_raw.extend(results)
            queries_issued.append(q)
        except Exception:
            queries_issued.append(f"{q} [FAILED]")

    # Deduplicate and tier-rank
    sources = _deduplicate_sources(all_raw)

    # Build claims from retrieved titles
    freshness_days = _freshness_to_days(freshness)
    claims = build_claims(topic, sources, freshness_days)

    # Extract visual facts and anti-cliche prompt directives (Phase 10.3)
    visual_facts = extract_visual_facts(topic, sources, claims)

    # Score and rank stories, selecting top stories (Phase 10.4)
    all_stories, top_stories = rank_stories(
        topic, sources, claims, top_n=top_n_stories
    )

    return ResearchPack(
        topic=topic,
        researched_at=researched_at,
        research_mode=ResearchMode.LIVE,
        provider=provider.name,
        queries_issued=queries_issued,
        claims=claims,
        sources=sources,
        visual_facts=visual_facts,
        stories=all_stories,
        top_stories=top_stories,
        status="ok",
    )


def _freshness_to_days(freshness: Optional[str]) -> Optional[int]:
    if not freshness:
        return None
    mapping = {"1d": 1, "7d": 7, "30d": 30, "1y": 365}
    return mapping.get(freshness)
